# Generated by Django 4.1.7 on 2023-03-16 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppFreeMarket', '0002_alter_buyer_id_alter_delivery_id_alter_seller_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
